### ISSUE TITLE
F06 - Adicionar mais opções de áreas/subáreas

### ISSUE THREAD

**Issue by tuxavier** [ThoughtWorksInc/transervicos#16]
Adicionar na base de dados as seguintes opções de áreas/subáreas no do CRUD serviços:

eventos / outros
moda / costura
higiene / limpeza
atendimento ao público / outros
alimentação / outros

adicionar idiomas como subarea de ensino

Adicionar tecnologia como uma área

**Comment by roselmamendes** [comment]
@tuxavier @brunapereira 
O Painel do Admin agora funciona para manter Áreas, mas eu tenho uma questão: em produção teremos que cadastrar as áreas na mão. É o que se espera?

Minha sugestão:
Coloquei toda a parte de popular Areas e Subareas no banco, no arquivo`seeds.rb`. Este arquivo existe no Rails para este tipo de tarefa. Com isso, para popular as respectivas tabelas basta chamar o comando **rake db:seed**, mesmo que adicionemos novas áreas e/ou subáreas.
Depois podemos colocar esse comando em um script de deploy. Assim teríamos o passo de adicionar listas fixas automatizado tanto para criação como para edição das mesmas. O que acham?

Fiquei na dúvida se a área Ensino (mencionada no cartão) se refere a área Educação. A principio coloquei Idioma como subarea de Educação.

Para finalizar esse cartão está faltando:
- Criar testes para o seeds.rb (não sou muito familiarizada com Rails, então deixei o approach do teste, se é que existe teste para esse arquivo, para o final);
- Colocar o cancan para o Painel de Admin, permitindo somente os admins.

**Comment by tuxavier** [comment]
@roselmamendes obrigada! Vou criar um card para adicionarmos o comando rake db:seed em um script de deploy :)

Está ok o idioma ser subárea de Educação =D

Vou criar um card separado para o cancan no Painel Admin, assim você pode finalizar esse card, ok?

(ah, e vou dar uma olhada agora no Painel Admin)
