### ISSUE TITLE
Filtros de busca na tela de serviços

### ISSUE THREAD

**Issue by tuxavier** [ThoughtWorksInc/transervicos#21]
O usuário deve poder buscar serviços por Estado e/ou Cidade e/ou  Nome do serviço.

O nome do serviço não precisa ser exatamente igual para ser retornado na lista de resultados ("contains"?).

**Comment by gconca** [comment]
Estou aprendendo Ruby e Ruby on Rails para fazer essa tarefa. Comecei a estudar dia 25/02 com a apresentação do Brizeno e sigo, após muitos problemas de ambiente na sexta-feira, fazendo o tutorial de Rails descrito em: http://guides.rubyonrails.org/getting_started.html
