### ISSUE TITLE
Adicionar campo "website" no contato do serviço

### ISSUE THREAD

**Issue by tuxavier** [ThoughtWorksInc/transervicos#39]
Adicionar campo não obrigatório no CRUD de serviços, na parte de contato do serviço

**Comment by gconca** [comment]
O campo foi acrescentado após o campo nome do serviço.

**Comment by gconca** [comment]
- o link, existente nas listagens de serviços ou no detalhe de um serviço específico, deve abrir em outra janela quando clicado.
