### ISSUE TITLE
Crear servidor de QA

### ISSUE THREAD

**Issue by tuxavier** [ThoughtWorksInc/transervicos#40]
Ver se é possível usar o servidor da Dani ou se precisa de outro.

**Comment by vtrbtf** [comment]
@tuxavier Ainda tentando achar uma alternativa para o  Heroku.
OpenShift: Bom, mas nao suporta totalmente nossa stack
Heroku Hobby:  US$ 16 
Jelastic: Plataforma ainda imatura. 
AWS Free Tier: Ainda analisando :)

**Comment by vtrbtf** [comment]
Então @tuxavier, pra não ficar só na comunicação verbal, resolvi mandar esse post com alguns pensamentos sobre a questão do ambiente no Transerviços.

**PaaS:**

Tentei fazer um approach de economia em relação a hospedagem, a partir disso, dei uma olhada nos serviços:
- Heroku  
- AWS
- Jelastic
- OpenShift 

Todos esses serviços também já hospedam o banco, mas sempre com algumas limitações. 

**Free Tier:**

Tirando o Jelastic, todos os serviços tem um free tier disponível para aplicações não criticas, mas sempre com  algumas limitações também. 
- Heroku
  Obrigatoriamente, a aplicação fica indisponível por 6h por dia
  Se a app não tiver trafego por mais de 30 min, a aplicação fica em idle
  Limitado a somente 1 server
  Host com 512MB RAM 
  Banco com limite de 10K linhas e com sleep obrigatório de 4h/mês. 
  Acesso limitado via ssh
- OpenShift 
  Se a app não tiver trafego por mais de 1 dia, a aplicação fica em idle
  Limitado a somente 1 server
  Host com 512MB RAM 
  Acesso limitado via ssh
  A plataforma não da suporte a nossa versão do ruby. Teriamos que ter um trabalho com provisionamento da maquina ( sem root privileges )  ou downgrade de versão, o que eu acho caído
- AWS 
  1GB de RAM. 
  Período gratis de 1 ano. 
  É obrigatório o uso de cartão de crédito. 
  Limite de 5GB de dados no banco. 

Pessoalmente, para a versão grátis, eu acho que a AWS é a melhor escolha, porém integrar o deploy automatizado na AWS pode ter um trabalho a mais. 
No Heroku, por exemplo, é bem mais tranquilo. 
A AWS também é beeeeem mais complexa que o Heroku, e dependendo de quem for manter a aplicação, pode fazer mais sentido deixar numa plataforma mais simples. 

Se quiser testar depois, eu te mostro o dashboard da AWS e como funciona. 
Também ja instalei um APM para aplicação la ( NewRelic ). 

**Sobre o OpenShift e Jelastic:**

   Ainda não tenho uma opinião 100% formada sobre, mas eu acho que a documentação da plataforma é bem ruim, alem do suporte que também não achei direito. 

   **Nenhum dos dois também tem integração com o Snap-CI :(**

O Jelastic só tem versão paga, e apesar de ser bem intuitivo, vi uns erros meio bizarros no ambiente la. 
Ja o OpenShift iria requerer um trabalho a mais, pois não suporta nossa versão ruby. 
Mas ainda to olhando para ver se acho algum ponto legal.

**Comment by pipklein** [comment]
Importante saber em relação aos servidores @roselmamendes  @kaofelix  @gconca  @tuxavier 
- Há suporte em língua portuguesa?
- Qual nível de conhecimento técnico em TI a pessoa que vai acessar o suporte precisa ter?
- Qual a disponibilidade do suporte?
- Está previsto em contrato tudo isso?
- Há diferenciação entre tamanho de cliente que utiliza o serviço?
- Qual o valor mensal? O que inclui nesse valor? 
- Qual a política de reajuste do valor e periodicidade?
- Como é a forma de pagamento? 
- Quantos usuários é possível criar para cada conta de acesso?
- As ações dos usuários são logadas?

**Comment by kaofelix** [comment]
Dani, respondendo o que eu sei pro Heroku:

**Há suporte em língua portuguesa?**
Infelizmente acho que não. 

**Qual nível de conhecimento técnico em TI a pessoa que vai acessar o suporte precisa ter?**
O Heroku tem um dashboard que é razoavelmente fácil de usar. A experiência de usuário dele acho bem intuitiva comparado com alternativas. E com o Snap configurado a pessoa nem precisaria saber git para fazer um deploy por exemplo.

**Qual a disponibilidade do suporte?**
De acordo com https://www.heroku.com/support o suporte gratuito é 12×5 (que eles chamam de horário comercial).

Eu sei que essa é uma preocupação grande tua, Dani, devido a experiências ruins passadas, mas por tudo que sei e ouço do Heroku, sequer ter a necessidade de suporte é uma possibilidade pequena. A infraestrutura deles é muito boa e eles tem muitos clientes: https://www.heroku.com/customers. Todos os clientes tem acesso ao mesmo dashboard e às mesmas opções, a única coisa extra que se compra é mais memória, poder de processamento, máquinas rodando em paralelo, add-ons, etc.

Por eles terem um nome grande hoje em dia eles tem muita visibilidade, então uma queda de serviços acaba sendo considerada um desastre de proporções épicas e vira notícia: https://gigaom.com/2011/04/21/more-than-100-sites-went-down-with-ec2-including-your-paas-provider/ (note que isso foi em 2011 e foi decorrente de uma queda da amazon).

**Está previsto em contrato tudo isso?**
Acredito que sim.

Há diferenciação entre tamanho de cliente que utiliza o serviço?
No suporte? Há diferentes planos. O suporte premium custa caro ($1000) e acho q é mais direcionado a clientes enterprise.

**Qual o valor mensal? O que inclui nesse valor?**
$7 pelo plano Hobby do servidor e $9 pelo plano Hobby do banco de dados. Isso inclui a disponibilidade do aplicativo o tempo inteiro. Outro detalhe que acabei de ver: o plano é rateado por segundo, isso é, só paga o tempo que o aplicativo foi utilizado mesmo. O exemplo que eles dão é, se o tempo de uso foi 1 dia total vc pagaria 1/30 do preço do plano (0,23 no caso de $7).

**Qual a política de reajuste do valor e periodicidade?**
Acho que eles não mudam o modelo de preços deles com frequência.

**Como é a forma de pagamento?**
Cartão de crédito internacional.

**Quantos usuários é possível criar para cada conta de acesso?**
Até onde eu sei é ilimitado. Basta dar acesso à aplicação para qualquer conta do heroku (ou convidar uma pessoa a fazer uma nova conta por email, acho q dá no mesmo).

**As ações dos usuários são logadas?**
Pelo que vi sim. Tem uma aba activity feed na página de gerência do aplicativo e lá mostra as principais ações executadas (por exemplo, deploys)
