### ISSUE TITLE
Campos de Estado e Cidade devem ser fixos

### ISSUE THREAD

**Issue by tuxavier** [ThoughtWorksInc/transervicos#43]
Atualmente esses campos (no crud serviço) são texto livre. Eles devem ser fixos.

**Comment by gconca** [comment]
Pesquisando sobre o tema vi que muitas pessoas colocam essas informações de estado/cidade no banco de dados, pegando a informação uma única vez de um arquivo e populando a base de dados.
Links de referência:
https://github.com/celsodantas/br_populate
