### ISSUE TITLE
Tentar cadastrar um serviço sem area causa NoMethodError

### ISSUE THREAD

**Issue by gconca** [ThoughtWorksInc/transervicos#57]
Ao se tentar cadastrar um serviço sem preencher os campos obrigatórios: Área e Subárea ocorre o erro: NoMethodError.

**Comment by tuxavier** [comment]
1) É como se a validação não estivesse funcionando.

2) Além disso, a página de erro apareceu genérica para mim, ao invés de uma página personalizada de erro do transerviços.

**Comment by gconca** [comment]
Foi criada uma tarefa separada para a criação de páginas de erro customizadas para o caso de ocorrerem erros 500, 404 e 422. Ver tarefa 60.
Essa tarefa está temporariamente suspensa para execução da tarefa 60, e será retomada em seguida.

**Comment by gconca** [comment]
Tarefa #60 ok!
