### ISSUE TITLE
Está faltando labels nas mensagens de erro na tela de Cadastro de Serviço

### ISSUE THREAD

**Issue by gconca** [ThoughtWorksInc/transervicos#59]
Na tela de cadastro de Serviços:
- tente cadastrar um serviço apenas com area e subárea
  Problema: aparecerão mensagens de validação de obrigatoriedade e validade sem o label do campo que causou a falha na validação

**Comment by tuxavier** [comment]
São os labels de "Nome do serviço oferecido" e "Descrição" que estão faltando, o resto está ok =)
