### ISSUE TITLE
Adicionar o http no back end (website)

### ISSUE THREAD

**Issue by tuxavier** [ThoughtWorksInc/transervicos#62]

**Comment by gconca** [comment]
A solução ficou da seguinte forma:
- No cadastro o usuário pode  ou não colocar http:// ou https:// no início da URL no campo website. A URL será validada afim de garantir que ela não contenha vírgulas, seja composta somente por número etc = seja uma URL com formato correto.
- Caso, no cadastro, o usuário não especifique a parte http ou https no campo website, será incluído http:// na URL antes de salvar o website no banco.

Resumindo, 2 partes:
- validação: a URL terá sua formatação (forma, não existência) validada.
- inclusão de protocolo: caso o usuário não tenha especificado protocolo, será colocado http como protocolo da URL antes de salvá-la no banco.
