### ISSUE TITLE
Colocar mensagem para avisar que site está em fase de teste

### ISSUE THREAD

**Issue by gconca** [ThoughtWorksInc/transervicos#65]
Colocar uma mensagem na primeira página para avisar que o site em questão é apenas um teste.

**Comment by gconca** [comment]
A primeira coisa a ser feita foi voltar o texto antigo, que existia na primeira página, para avisar aos TWers que o site estava em fase de testes e que qualquer problema ou sugestão era necessário entrar em contato com a Turah por email.

**Comment by tuxavier** [comment]
Oi Conquinha!
Trocar "Preview" por "Teste".

E trocar o texto por:

Olá, gente!

Estamos fazendo o pré-lançamento da 1a versão do Transerviços para a Roda de Conversa e pessoas próximas =)

O objetivo é apresentar a versão teste do site e contar com a ajuda de todos vocês para coletar feedbacks e registros de possíveis erros até terça, 12/04.
Compartilhe seu feedback mandando um email para turahxavierbr@gmail.com com o assunto "Transerviços - Feedback".
