### ISSUE TITLE
Avaliação de Serviços

### ISSUE THREAD

**Issue by pipklein** [ThoughtWorksInc/transervicos#66]
Criar sistema de avaliação do tipo "Indico" e "Não indico", com contador ao lado. O usuário pode avaliar mais de uma vez aumentando o contador.

**Comment by gconca** [comment]
_Acrescentar:_
- trocar o texto Gostei/Não Gostei para o thumbs-up/down fo font-awesome.
- colocar o número de gostei/não gostei entre parênteses
- colocar Gostei/Não Gostei na página de detalhe de serviço. Colocar ao lado do título do serviço

_Extra - ver se como fazer:_
- Trocar de thumbs up hollow e preenchido dependendo se o usuário/ip já votou no serviço

**Comment by gconca** [comment]
Pode ser interessante colocar uns índices nas tabelas de votação e já previamente guardar os votos up e down em cada serviço, para fazer menos acessos ao banco e ter de fazer joins
