### ISSUE TITLE
Filtrar palavras proibidas

### ISSUE THREAD

**Issue by pipklein** [ThoughtWorksInc/transervicos#69]
Na descrição do serviço, filtrar palavras não permitidas a serem incluídas em tabela no banco de dados, assim, quando a pessoa clicar em salvar o sistema emitirá mensagem frisando: "Não foi possível salvar o serviço pois há palavras não permitidas na descrição. As palavras são: xxx, yyy, zzz".

**Comment by kaofelix** [comment]
@pipklein uma pergunta: na lista de palavras da mensagem 'xxx, yyy, zzz' seria para mostrar todas as palavras proibidas pelo sistema ou apenas as palavras proibidas que a pessoa cadastrando o serviço colocou na sua descrição?

**Comment by kaofelix** [comment]
Agora lendo de novo a mensagem parece mais claro pra mim q é só as palavras proibidas que aparecem no texto da pessoa é que fariam parte da mensagem. Eu vou supor esse caminho por enquanto e qualquer coisa a gente muda depois :)

**Comment by pipklein** [comment]
Mostrar apenas as palavras proibidas que impedem o serviço de ser gravado @kaofelix .
